"""
Author: Rodion Calistru, rcalistr@purdue.edu
Assignment: 08.5 - Number Reader
Date: 10/24/2022

Description:
    Program reads in the file generated by number_writer program
    and computes various data about the numbers in the file:
    max, min, sum and average

Contributors:
    Rodion Calistru, rcalistr@purdue.edu [repeat for each]

My contributor(s) helped me:
    [ ] understand the assignment expectations without
        telling me how they will approach it.
    [ ] understand different ways to think about a solution
        without helping me plan my solution.
    [ ] think through the meaning of a specific error or
        bug present in my code without looking at my code.
    Note that if you helped somebody else with their code, you
    have to list that person as a contributor.

Academic Integrity Statement:
    I have not used source code obtained from any unauthorized
    source, either modified or unmodified; nor have I provided
    another student access to my code.  The project I am
    submitting is my own original work.
"""

"""Import additional modules below this line (starting with unit 6)."""


"""Write new functions below this line (starting with unit 4)."""


def main():
    data = []
    m = []
    with open('random_numbers.txt','r') as fo:
        for line in fo:
            data.append(line.rstrip()) #Read the lines from the file into the list
    
    for n in data:
        m.append(float(n)) #Convert the strings into float values
    
    print(f"{len(m):,d} numbers were read from the file.")
    print(f"Min: {min(m):,.0f}")
    print(f"Max: {max(m):,.0f}")
    print(f"Sum: {sum(m):,.0f}")
    print(f"Avg: {sum(m)/len(m):,.1f}")


"""Do not change anything below this line."""
if __name__ == "__main__":
    main()
